python ./run_pretraining_clip_node2vec.py \
  --text_model_name_or_path \
  microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract \
  --output_dir \
  [path_to_the_output] \
  --data_dir \
  [path_to_the_input] \
  --group_file \
  [path_to_the_pathway_grouping_file] \
  --dataloader_num_workers \
  8 \
  --remove_unused_columns \
  False \
  --label_names \
  label \
  --do_train \
  --do_eval \
  --learning_rate \
  1e-5 \
  --weight_decay \
  0.05 \
  --num_train_epochs \
  300 \
  --train_val_split \
  0.15 \
  --per_device_train_batch_size \
  256 \
  --per_device_eval_batch_size \
  32 \
  --logging_strategy \
  steps \
  --logging_steps \
  10 \
  --evaluation_strategy \
  steps \
  --eval_steps \
  3000 \
  --save_strategy \
  steps \
  --save_steps \
  3000 \
  --load_best_model_at_end \
  True \
  --save_total_limit \
  30 \
  --greater_is_better \
  True \
  --metric_for_best_model \
  eval_top_1_accuracy \
  --seed \
  1337 \
  --log_level \
  debug \
  --report_to \
  none \
  --project_name \
  gext_za_clip_onclass \
  --run_name \
  ts_iter2_0.1_node2vec_cell_name_kegg_only